let a = true
let b = String
let o = 10 > 7
let s = Boolean
let n = Int32Array
let m = Boolean('yes')
let l = String("no")
let f = String('emmo + sigma + giga chad + chad')
let yes = String ("1 - 2 + 8 + 19 + 77 + 33 - 8 - 3 - 05")
let j = racxa 
let g = true && false
let q  = 1
let w = 3
let r = 0 
let y = i
let i = KeyboardEvent
let x = HTMLHRElement
let z = history 
let p = getComputedStyle
let pp = KeyboardEvent